data:
  dir: "./data/cat_dog"
  # Sampling options for dataloader
  train:
    augmentation:
      # if there is neccesary to optimize augmentation, we will use this
      sift:   # circle   or   default   or   blur_circle
      edge: 
      gabor:
    shuffle: True
    batch_size: 32
    n_workers: 1
  val:
    shuffle: False
    batch_size: 1
    n_workers: 1
  test:
    shuffle: False
    batch_size: 1
    n_workers: 1

network:
  backbone: "resnet50"
  n_cv: 0

run:
  epoch: 100
  val_interval: 2
  optimizer:
    name: "adam"
    lr: 5.0e-5
  scheduler: # use this if neccessary
