data:
  dir: "/data/stl10"
  # Sampling options for dataloader
  train:
    augmentation:
      # if there is neccesary to optimize augmentation, we will use this
    shuffle: True
    batch_size: 1
    n_workers: 1
  val:
    batch_size: 1
    n_workers: 1
  test:
    batch_size: 1
    n_workers: 1

network:
  backbone: "resnet18"
  n_class: 10
  n_cv: 1

run:
  epoch: 10
  val_interval: 5
  optimizer:
    name: "adam"
    lr: 5e-5
  scheduler: # use this if neccessary