data:
  dir: "./data_for_test/stl10_small" # directory path or "CIFAR10" or "CIFAR100"
  resize: 512 # Resize factor, integer number
  # Sampling options for dataloader
  train:
    augmentation:
      sift:   # circle   or   default   or   blur_circle
      edge: 
      gabor: 
      perspective: # True or False
    shuffle: True
    batch_size: 10
    n_workers: 1
  val:
    shuffle: False
    batch_size: 1
    n_workers: 1
  test:
    shuffle: False
    batch_size: 1
    n_workers: 1

network:
  backbone: "resnet18"
  n_cv: 0
  gabor:

run:
  epoch: 10
  val_interval: 2
  optimizer:
    name: "adam"
    lr: 5.0e-5
  scheduler: # use this if neccessary